server:
  port: 8081

spring:
  config:
    activate:
      on-profile: sandbox
  datasource:
    url: jdbc:h2:tcp://localhost/./user-sample
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  devtools:
    livereload:
      enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
